const abreviacoes = [
    [/\—/gi, '\n '],
    [/\*/gi, ' '],
    [/-\n/gi, ''],
    [/\n/gi, ' '],
    [/•/gi, "; "],
    [/\b\:/gi, ". "],
    [/\bex\./gi, "exemplo"],
    [/\bEx\./gi, "Exemplo"],
    [/\bex\./gi, "exemplo"],
    [/\bEx\./gi, "Exemplo"],
    [/\bexs\./gi, "exemplos"],
    [/\bExs\./gi, "Exemplos"],
    [/\bexs\./gi, "exemplos"],
    [/\bExs\./gi, "Exemplos"],
    [/\bDr\./gi, "Doutor"],
    [/\bDra\./gi, "Doutora"],
    [/\bSr\./gi, "Senhor"],
    [/\bSra\./gi, "Senhora"],
    [/\bSrs\./gi, "Senhores"],
    [/\bSrta\./gi, "Senhorita"],
    [/\bProf\./gi, "Professor"],
    [/\bProfa\./gi, "Professora"],
    [/\bEng\./gi, "Engenheiro"],
    [/\bArq\./gi, "Arquiteto"],
    [/\bAdv\./gi, "Advogado"],
    [/\bCel\./gi, "Coronel"],
    [/\bGen\./gi, "General"],
    [/\bCap\./gi, "Capitão"],
    [/\bTen\./gi, "Tenente"],
    [/\bMaj\./gi, "Major"],
    [/\bMin\./gi, "Ministro"],
    [/\bDep\./gi, "Deputado"],
    [/\bDepª\./gi, "Deputada"],
    [/\bSen\./gi, "Senador"],
    [/\bGov\./gi, "Governador"],
    [/\bPres\./gi, "Presidente"],
    [/\bExmo\./gi, "Excelentíssimo"],
    [/\bExma\./gi, "Excelentíssima"],
    [/\bIlmo\./gi, "Ilustríssimo"],
    [/\bArt\./gi, "Artigo"],
    [/\bArts\./gi, "Artigos"],
    [/\bCap\./gi, "Capítulo"],
    [/\bVol\./gi, "Volume"],
    [/\bPág\./gi, "Página"],
    [/\bPgs\./gi, "Páginas"],
    [/\bEd\./gi, "Edição"],
    [/\bEds\./gi, "Edições"],
    [/\bAv\./gi, "Avenida"],
    [/\bR\./gi, "Rua"],
    [/\bRod\./gi, "Rodovia"],
    [/\bEst\./gi, "Estrada"],
    [/\bNº\b/gi, "Número"],
    [/\bN°\b/gi, "Número"],
    [/\bnº\b/gi, "número"],
    [/\betc\./gi, "etcetera"],
    [/\bObs\./gi, "Observação"],
    [/\bRef\./gi, "Referência"],
    [/\bResp\./gi, "Responsável"],
    [/\bDepto\./gi, "Departamento"],
    [/\bAdm\./gi, "Administração"],
    [/\bEmp\./gi, "Empresa"],
    [/\bTel\./gi, "Telefone"],
    [/\bCEP\b/g, "CEP"],
    [/\bCPF\b/g, "C P F"],
    [/\bCNPJ\b/g, "C N P J"],
    [/\bRG\b/g, "R G"],
    [/\bCNH\b/g, "C N H"],
    [/\bHTML\b/g, "H T M L"],
    [/\bCSS\b/g, "C S S"],
    [/\bJS\b/g, "J S"],
    [/\bAPI\b/g, "A P I"],
    [/\bSQL\b/g, "S Q L"],
    [/\bPDF\b/g, "P D F"],
    [/\bUSB\b/g, "U S B"],
    [/\bWi-?Fi\b/gi, "Uai Fai"],
    [/\bwww\./gi, "www ponto "],
    [/\.com\b/gi, " ponto com"],
    [/\.com\.br\b/gi, " ponto com ponto br"]
];
export { abreviacoes };