const ordinais = {
    1: ["primeiro", "primeira"],
    2: ["segundo", "segunda"],
    3: ["terceiro", "terceira"],
    4: ["quarto", "quarta"],
    5: ["quinto", "quinta"],
    6: ["sexto", "sexta"],
    7: ["sétimo", "sétima"],
    8: ["oitavo", "oitava"],
    9: ["nono", "nona"],
    10: ["décimo", "décima"],
    11: ["décimo primeiro", "décima primeira"],
    12: ["décimo segundo", "décima segunda"],
    13: ["décimo terceiro", "décima terceira"],
    14: ["décimo quarto", "décima quarta"],
    15: ["décimo quinto", "décima quinta"],
    16: ["décimo sexto", "décima sexta"],
    17: ["décimo sétimo", "décima sétima"],
    18: ["décimo oitavo", "décima oitava"],
    19: ["décimo nono", "décima nona"],
    20: ["vigésimo", "vigésima"],
    21: ["vigésimo primeiro", "vigésima primeira"],
    22: ["vigésimo segundo", "vigésima segunda"],
    23: ["vigésimo terceiro", "vigésima terceira"],
    24: ["vigésimo quarto", "vigésima quarta"],
    25: ["vigésimo quinto", "vigésima quinta"],
    26: ["vigésimo sexto", "vigésima sexta"],
    27: ["vigésimo sétimo", "vigésima sétima"],
    28: ["vigésimo oitavo", "vigésima oitava"],
    29: ["vigésimo nono", "vigésima nona"],
    30: ["trigésimo", "trigésima"],
    31: ["trigésimo primeiro", "trigésima primeira"],
    32: ["trigésimo segundo", "trigésima segunda"],
    33: ["trigésimo terceiro", "trigésima terceira"],
    34: ["trigésimo quarto", "trigésima quarta"],
    35: ["trigésimo quinto", "trigésima quinta"],
    36: ["trigésimo sexto", "trigésima sexta"],
    37: ["trigésimo sétimo", "trigésima sétima"],
    38: ["trigésimo oitavo", "trigésima oitava"],
    39: ["trigésimo nono", "trigésima nona"],
    40: ["quadragésimo", "quadragésima"],
    41: ["quadragésimo primeiro", "quadragésima primeira"],
    42: ["quadragésimo segundo", "quadragésima segunda"],
    43: ["quadragésimo terceiro", "quadragésima terceira"],
    44: ["quadragésimo quarto", "quadragésima quarta"],
    45: ["quadragésimo quinto", "quadragésima quinta"],
    46: ["quadragésimo sexto", "quadragésima sexta"],
    47: ["quadragésimo sétimo", "quadragésima sétima"],
    48: ["quadragésimo oitavo", "quadragésima oitava"],
    49: ["quadragésimo nono", "quadragésima nona"],
    50: ["quinquagésimo", "quinquagésima"],
    51: ["quinquagésimo primeiro", "quinquagésima primeira"],
    52: ["quinquagésimo segundo", "quinquagésima segunda"],
    53: ["quinquagésimo terceiro", "quinquagésima terceira"],
    54: ["quinquagésimo quarto", "quinquagésima quarta"],
    55: ["quinquagésimo quinto", "quinquagésima quinta"],
    56: ["quinquagésimo sexto", "quinquagésima sexta"],
    57: ["quinquagésimo sétimo", "quinquagésima sétima"],
    58: ["quinquagésimo oitavo", "quinquagésima oitava"],
    59: ["quinquagésimo nono", "quinquagésima nona"],
    60: ["sexagésimo", "sexagésima"],
    61: ["sexagésimo primeiro", "sexagésima primeira"],
    62: ["sexagésimo segundo", "sexagésima segunda"],
    63: ["sexagésimo terceiro", "sexagésima terceira"],
    64: ["sexagésimo quarto", "sexagésima quarta"],
    65: ["sexagésimo quinto", "sexagésima quinta"],
    66: ["sexagésimo sexto", "sexagésima sexta"],
    67: ["sexagésimo sétimo", "sexagésima sétima"],
    68: ["sexagésimo oitavo", "sexagésima oitava"],
    69: ["sexagésimo nono", "sexagésima nona"],
    70: ["septuagésimo", "septuagésima"],
    71: ["septuagésimo primeiro", "septuagésima primeira"],
    72: ["septuagésimo segundo", "septuagésima segunda"],
    73: ["septuagésimo terceiro", "septuagésima terceira"],
    74: ["septuagésimo quarto", "septuagésima quarta"],
    75: ["septuagésimo quinto", "septuagésima quinta"],
    76: ["septuagésimo sexto", "septuagésima sexta"],
    77: ["septuagésimo sétimo", "septuagésima sétima"],
    78: ["septuagésimo oitavo", "septuagésima oitava"],
    79: ["septuagésimo nono", "septuagésima nona"],
    80: ["octogésimo", "octogésima"],
    81: ["octogésimo primeiro", "octogésima primeira"],
    82: ["octogésimo segundo", "octogésima segunda"],
    83: ["octogésimo terceiro", "octogésima terceira"],
    84: ["octogésimo quarto", "octogésima quarta"],
    85: ["octogésimo quinto", "octogésima quinta"],
    86: ["octogésimo sexto", "octogésima sexta"],
    87: ["octogésimo sétimo", "octogésima sétima"],
    88: ["octogésimo oitavo", "octogésima oitava"],
    89: ["octogésimo nono", "octogésima nona"],
    90: ["nonagésimo", "nonagésima"],
    91: ["nonagésimo primeiro", "nonagésima primeira"],
    92: ["nonagésimo segundo", "nonagésima segunda"],
    93: ["nonagésimo terceiro", "nonagésima terceira"],
    94: ["nonagésimo quarto", "nonagésima quarta"],
    95: ["nonagésimo quinto", "nonagésima quinta"],
    96: ["nonagésimo sexto", "nonagésima sexta"],
    97: ["nonagésimo sétimo", "nonagésima sétima"],
    98: ["nonagésimo oitavo", "nonagésima oitava"],
    99: ["nonagésimo nono", "nonagésima nona"],
    100: ["centésimo", "centésima"]
};
export { ordinais };